name: MineTwitch
version: @version@
main: com.github.risbun.minetwitch.MainClass
api-version: 1.16
commands:
  minetwitch:
    aliases: mt
    description: MineTwitch
    usage: /minetwitch
    permission: op
  test:
    description: testing commands
    usage: /test
    permission: op