name: MineTwitch
version: @version@
main: com.github.risbun.minetwitch.Main
api-version: 1.17
commands:
  minetwitch:
    aliases: mt
    description: MineTwitch
    usage: /minetwitch
  test:
    description: testing commands
    usage: /test